server1:
+  build: ./
+  expose:
+    - "8080"
+
+server2:
+  build: ./
+  expose:
+    - "8080"
+
+server3:
+  build: ./
+  expose:
+    - "8080"
+
+nginx:
+  build: ./nginx/
+  ports:
+    - "80:80"
+  links:
+    - server1
+    - server2
+    - server3 
